# Makefile

all: exec_1 exec_2 exec_3 exec_4

prime_mpi: prime_mpi.c
	mpicc -o prime_mpi prime_mpi.c

exec_1: prime_mpi
	cp $< $@

exec_2: prime_mpi
	cp $< $@

exec_3: prime_mpi
	cp $< $@

exec_4: prime_mpi
	cp $< $@

