#!/bin/bash

if [ $# == "0" ] ; then
  export MPIF90_F90=ifort
  echo "export MPIF90_F90=ifort"
else
  export MPIF90_F90=$1
  echo "export MPIF90_F90=$1"
fi

case $MPIF90_F90 in
  ifort)
    echo 'ifort -DUSEMPI -P timers_exp.F -o timers_exp.f'
    echo 'mpif90 -O0 -o timers_exp.x timers_exp.f'
    ifort -DUSEMPI -P timers_exp.F -o timers_exp.f
    mpif90 -O0 -o timers_exp.x timers_exp.f ;;
  gfortran)
    echo 'mpif90 -DUSEMPI -o timers_exp.x timers_exp.F'
    mpif90 -DUSEMPI -o timers_exp.x timers_exp.F ;;
  *)
    echo "That string not recognized as a valid compiler." ;;
esac

